package com.ilgiyebo.domain.campus.entity;

public enum TypeActivity {
    CAFE, CONVENIENCE_STORE, RESTAURANT, LECTURE_ROOM, STUDY_ROOM, MEETING_ROOM, ELEVATOR, BENCH, OTHER,
    LOUNGE, REST_ROOM, ENTRANCE, INTERSECTION, OUTDOOR, STAIRWAY
}
