-- 기존 PLAN_ENTRY (JSON 기반) 테이블 삭제
DROP TABLE IF EXISTS PLAN_ENTRY;

-- TIMETABLE_ENTRY를 PLAN_ENTRY로 리네임
ALTER TABLE TIMETABLE_ENTRY RENAME TO PLAN_ENTRY;

-- course_name → name 컬럼 변경
ALTER TABLE PLAN_ENTRY CHANGE COLUMN course_name name VARCHAR(255) NULL;

-- type 컬럼 추가 (PlanItemType enum: CLASS, FREE, ACTIVITY)
ALTER TABLE PLAN_ENTRY ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'CLASS';
