-- V3: BaseSchema 통합을 위해 누락된 created_at, updated_at 컬럼 추가

-- TIMETABLE_ENTRY: created_at, updated_at 추가
ALTER TABLE TIMETABLE_ENTRY ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TIMETABLE_ENTRY ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- NOTIFICATION_SETTING: created_at, updated_at 추가
ALTER TABLE NOTIFICATION_SETTING ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE NOTIFICATION_SETTING ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- CHAT_SESSION: created_at, updated_at 추가
ALTER TABLE CHAT_SESSION ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CHAT_SESSION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- GAME_SESSION: created_at, updated_at 추가
ALTER TABLE GAME_SESSION ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE GAME_SESSION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- MISSION: created_at, updated_at 추가
ALTER TABLE MISSION ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MISSION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- AI_REVIEW_QUESTION: created_at, updated_at 추가
ALTER TABLE AI_REVIEW_QUESTION ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE AI_REVIEW_QUESTION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- INTERACTION: created_at 추가 (updated_at은 이미 존재)
ALTER TABLE INTERACTION ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 기존 테이블들의 updated_at 컬럼 추가 (없는 경우)
-- SLOT
ALTER TABLE SLOT ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- MATCH
ALTER TABLE `MATCH` ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- DIARY_ENTRY
ALTER TABLE DIARY_ENTRY ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- PLAN_ENTRY
ALTER TABLE PLAN_ENTRY ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- CHAT_MESSAGE
ALTER TABLE CHAT_MESSAGE ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- REVIEW
ALTER TABLE REVIEW ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- REVIEW_SESSION
ALTER TABLE REVIEW_SESSION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- HINT_QUESTION
ALTER TABLE HINT_QUESTION ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- EXP_HISTORY
ALTER TABLE EXP_HISTORY ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- REPORT
ALTER TABLE REPORT ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- BLOCK
ALTER TABLE `BLOCK` ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
