-- V3: SLOT 테이블 구조 변경 - 속성 컬럼 제거, priority 컬럼 추가
ALTER TABLE SLOT DROP COLUMN hobbies;
ALTER TABLE SLOT DROP COLUMN interests;
ALTER TABLE SLOT DROP COLUMN ideal_type;
ALTER TABLE SLOT ADD COLUMN priority ENUM('HOBBY','INTEREST','IDEAL_TYPE') NOT NULL DEFAULT 'HOBBY' AFTER user_id;
