-- V4: 모든 ENUM 값을 대문자로 변경

-- SLOT.status
ALTER TABLE SLOT MODIFY COLUMN status ENUM('EMPTY','ACTIVE','COMPLETED') NOT NULL DEFAULT 'EMPTY';
UPDATE SLOT SET status = UPPER(status);

-- MATCH.status
ALTER TABLE `MATCH` MODIFY COLUMN status ENUM('ACTIVE','COMPLETED','TERMINATED') NOT NULL DEFAULT 'ACTIVE';
UPDATE `MATCH` SET status = UPPER(status);

-- INTERACTION.stage_status
ALTER TABLE INTERACTION MODIFY COLUMN stage_status ENUM('IN_PROGRESS','WAITING','COMPLETED','TERMINATED') NOT NULL DEFAULT 'IN_PROGRESS';
UPDATE INTERACTION SET stage_status = UPPER(stage_status);

-- DIARY_ENTRY.emotion_tag
ALTER TABLE DIARY_ENTRY MODIFY COLUMN emotion_tag ENUM('HAPPY','SAD','ANGRY','ANXIOUS','CALM','EXCITED','TIRED') NULL;
UPDATE DIARY_ENTRY SET emotion_tag = UPPER(emotion_tag) WHERE emotion_tag IS NOT NULL;

-- CHAT_SESSION.status
ALTER TABLE CHAT_SESSION MODIFY COLUMN status ENUM('ACTIVE','ENDED') NOT NULL DEFAULT 'ACTIVE';
UPDATE CHAT_SESSION SET status = UPPER(status);

-- GAME_SESSION.status
ALTER TABLE GAME_SESSION MODIFY COLUMN status ENUM('WAITING','IN_PROGRESS','COMPLETED') NOT NULL DEFAULT 'WAITING';
UPDATE GAME_SESSION SET status = UPPER(status);

-- MISSION.status
ALTER TABLE MISSION MODIFY COLUMN status ENUM('PENDING','CONFIRMED','EXPIRED') NOT NULL DEFAULT 'PENDING';
UPDATE MISSION SET status = UPPER(status);

-- REVIEW.mode
ALTER TABLE REVIEW MODIFY COLUMN mode ENUM('AI_ASSISTED','DIRECT') NOT NULL;
UPDATE REVIEW SET mode = UPPER(mode);

-- REVIEW_SESSION.mode
ALTER TABLE REVIEW_SESSION MODIFY COLUMN mode ENUM('AI_ASSISTED','DIRECT') NOT NULL;
UPDATE REVIEW_SESSION SET mode = UPPER(mode);

-- REVIEW_SESSION.status
ALTER TABLE REVIEW_SESSION MODIFY COLUMN status ENUM('IN_PROGRESS','GENERATED','COMPLETED') NOT NULL DEFAULT 'IN_PROGRESS';
UPDATE REVIEW_SESSION SET status = UPPER(status);

-- HINT_QUESTION.status
ALTER TABLE HINT_QUESTION MODIFY COLUMN status ENUM('PENDING','ANSWERED') NOT NULL DEFAULT 'PENDING';
UPDATE HINT_QUESTION SET status = UPPER(status);

-- EXP_HISTORY.activity
ALTER TABLE EXP_HISTORY MODIFY COLUMN activity ENUM('DIARY_WRITE','DIARY_STREAK_BONUS','PLANNER_WRITE','QUIZ_COMPLETE','CHAT_PARTICIPATE','GAME_COMPLETE','MISSION_COMPLETE','REVIEW_WRITE') NOT NULL;
UPDATE EXP_HISTORY SET activity = UPPER(activity);

-- REPORT.status
ALTER TABLE REPORT MODIFY COLUMN status ENUM('PENDING','REVIEWED','RESOLVED') NOT NULL DEFAULT 'PENDING';
UPDATE REPORT SET status = UPPER(status);

-- CAMPUS_BUILDING.purpose
ALTER TABLE CAMPUS_BUILDING MODIFY COLUMN purpose ENUM('LECTURE','RESTAURANT','CAFE','LIBRARY','GYM','ADMIN','DORMITORY','OTHER') NOT NULL;
UPDATE CAMPUS_BUILDING SET purpose = UPPER(purpose);

-- CAMPUS_VENUE.type
ALTER TABLE CAMPUS_VENUE MODIFY COLUMN type ENUM('CAFE','CONVENIENCE_STORE','BENCH','PLAZA','PARK','FOOD_COURT','STUDY_ROOM','OTHER') NOT NULL;
UPDATE CAMPUS_VENUE SET type = UPPER(type);
