package com.ilgiyebo.domain.exp.entity;

public enum ExpActivity {
    DIARY_WRITE, DIARY_STREAK_BONUS, PLANNER_WRITE, QUIZ_COMPLETE,
    CHAT_PARTICIPATE, GAME_COMPLETE, MISSION_COMPLETE, REVIEW_WRITE,
    HINT_ANSWER
}
