spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.CredentialsProviderAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.RegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: ap-northeast-2
    sqs:
      quiz-request-queue: local-quiz-request
      quiz-response-queue: local-quiz-response
      retro-request-queue: local-retro-request
      retro-response-queue: local-retro-response
      diary-request-queue: local-diary-request
      diary-response-queue: local-diary-response
    bedrock:
      model-id: local-model
